---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Annie Nguyen (ahn539)

#### Introduction 

The women's rights movement has made great strides since the late 19th century. Literacy rates for girls have continued to rise, and the world is  beginning to witness women assume higher positions of power. For many years, women's representation in government has been sparse, but because of better access to education, today there is stronger female representation in Congress and in Parliaments across the globe. 

This project analyzes the change in literacy rates for girls by country and examines the progress of women's representation in government. The `years` data set contains the mean number of years women (aged 15 to 44) were in school; the `ratio` data set contains the percent ratio of girls to boys in primary and secondary education; the `parliament` data set denotes the percentage of women in parliamentary positions. Each observation is recorded by country and year.

```{R}
library(tidyverse)
library(gt)
years <- read_csv("mean_years_in_school.csv")
ratio <- read_csv("ratio_girls_to_boys_in_school_perc.csv")
parliament <- read_csv("wn_bothhouses_c.csv")
```

#### Tidying: Reshaping

The data sets were tidied using the `pivot_longer` function. The data for years were pivoted, and the values column was renamed to their respective variable name.

```{R}
years %>% pivot_longer(-1, names_to='year', values_to='mean_yrs') ->years
glimpse(years)
ratio %>% pivot_longer(-1, names_to='year', values_to='ratio') -> ratio
glimpse(ratio)
parliament %>% pivot_longer(-1, names_to='year', values_to='perc_parliament') -> parliament
glimpse(parliament)
parliament %>% pivot_wider(names_from = 'year', values_from = 'perc_parliament') -> parliament_wider
head(parliament_wider)
```

    
#### Joining/Merging

```{R}
years %>% summarise(countries=n_distinct(country), years=n_distinct(year))
ratio%>% summarise(countries=n_distinct(country), years=n_distinct(year))
parliament %>% summarise(countries=n_distinct(country), years=n_distinct(year))
```
Before joining, the `years` data set has 7000 observations, `ratio` has 10,200 observations, and the `parliament` data set has 14,668 observations. In the `years` data set, there are 175 distinct countries, 200 countries in the `ratio` set, and 193 countries in the `parliament` set. 

```{R}
setdiff(years$country,ratio$country)
setdiff(ratio$country,years$country)

setdiff(years$country,parliament$country)
setdiff(parliament$country,years$country)

setdiff(ratio$country,parliament$country)
setdiff(parliament$country,ratio$country)
```
Using the `setdiff` function one can identify which countries from the first set is not in the second set. The listed countries above represent countries from the first data set that were excluded from the second. 

```{R}
inner_join(years,ratio) %>% inner_join(parliament) %>% summarise(n_distinct(country))
```
Across the three data sets, they share 170 countries in common.

```{R}
full_join(years,ratio) %>% full_join(parliament)->join

join %>% filter_at(vars(mean_yrs,ratio,perc_parliament),any_vars(!is.na(.))) -> joined_data
glimpse(joined_data)
```

The three data sets are joined by country and year using the full_join function in order to retain as many relevant data points as possible. However, rows where there are no data available for all three variables are filtered out. After filtering the data, 3,562 observations were dropped.

####  Wrangling

```{R}
joined_data %>% mutate(country=str_replace_all(country,'[- ]','')) %>% select(-year) %>% group_by(country) %>% summarise_all(function(x) mean(x,na.rm = T)) %>% arrange(-perc_parliament)
```

Grouping the data by countries, each column averages the available data points to yield the overall average for 'mean years in school,' 'ratio of girls to boys in school,' and the 'percent of women in parliamentary position,' respectively. The data were then re-arrange to show the countries with the highest percentage of women in parliament in descending order. Outputs of `NaN` indicates that no data was available for that particular country.

```{R}
joined_data %>% filter(year>2009) %>% select(country,perc_parliament) %>% group_by(country) %>% na.omit %>% summarise(avg_perc=mean(perc_parliament),sd=sd(perc_parliament), var=var(perc_parliament), count=n(),min=min(perc_parliament),max=max(perc_parliament)) %>% arrange(-avg_perc) 
```
Looking at the available data points for 'percentage of women in parliament' after 2009, the mean, standard deviation, variance, count (number of available data points), min, and max values are calculated for each country, respectively, and then arranged in descending order from the greatest average percent of women in parliament. Between 2000 and 2019, Rwanda, Sweden, and Cuba have the highest female representation in parliament compared to the United States, which is ranked 85th and has an average of 20.58%.

According to UNICEF, countries that have reached "gender parity" (or provides equal access to education for both boys and girls) have a ratio between 0.97 and 1.03. Examining only the data from the past decade (from 2010-2019), the following countries still have the greatest disparity in education access between genders:

```{R}
joined_data %>% filter(year>2009) %>% select(-year,-mean_yrs) %>% group_by(country) %>% summarise_all(function(x) mean(x,na.rm = T))%>% mutate(disparity=abs(ratio-1), parity_achieved = if_else(ratio<0.97|ratio>1.03,'False','True')) %>% arrange(-disparity) %>% head %>% gt %>% 
  tab_header(title=md("**Disparity in Access to Education**"),
             subtitle=md("Quantifying disparity in education and comparing to % of women in parliament")) %>%
  tab_spanner(label="Variables", columns=c('ratio','perc_parliament','disparity'))
```
Disparity was calculated by finding the absolute difference in magnitude between the value of the ratio and 1. Angola, Afghanistan and South Sudan have the greatest disparity in access to education between males and females. It is interesting to note that although disparity in these three countries are the greatest, average female representation in parliament is over 25% in all three countries.

#### Visualizing

```{R}
joined_data %>% filter(year>2009) %>% select(-year,-mean_yrs) %>% group_by(country) %>% summarise_all(function(x) mean(x,na.rm = T)) %>% mutate(disparity=abs(ratio-1)) %>% arrange(-disparity) -> joined_disparity
joined_disparity %>% filter(!is.na(disparity)) %>% tail
joined_disparity %>% head
joined_data %>% filter(country==c('Angola','Afghanistan','United States','South Africa','Oman'))  %>% ggplot(aes(x=year,y=perc_parliament,color=country,group=country)) +geom_point()+ geom_line()+theme(axis.text.x = element_text(angle = 90))+scale_x_discrete(breaks=c(1950,1960,1970,1980,1990,2000,2010,2019)) +labs(title = 'Year vs. % women in parliament') +xlab('Year') +ylab('% women in parliament')
```

In the plot above, the two countries with the highest disparity in education for males and females (Afghanistan and Angola) were plotted with two of the countries with some of the lowest disparities (South Africa and Oman). The United States was included as reference. The United States had the highest female representation in legislature before 1975, and countries like South Africa and Afghanistan have far surpassed the U.S. after the turn of the century.

```{R}
joined_data %>% filter(!is.na(mean_yrs),!is.na(ratio)) %>% group_by(country) %>% summarise(yrs_in_school=mean(mean_yrs), avg_ratio=mean(ratio)) %>% ggplot(aes(x=yrs_in_school,y=avg_ratio)) + geom_point() +geom_smooth(method='loess')+labs(title = 'Years in School vs. Ratio of Girls to Boys in School') +xlab('Years in School') +ylab('ratio of girls to boys')
```

The plot above represents the relationship between 'gender parity' and the number of years girls spend in school. Each point of the graph represents a single country. As the ratio reaches 1, females are more likely to remain in school for longer.

```{R}
joined_disparity %>% filter(!is.na(perc_parliament),!is.na(disparity)) %>% group_by(country) %>% summarise(avg_perc=mean(perc_parliament), avg_disparity=mean(disparity)) %>% ggplot(aes(x=avg_disparity,y=avg_perc)) + geom_point() +geom_smooth(method=lm)+scale_y_continuous(breaks = c(0,10,20,30,40,50))+labs(title = 'Gender Disparity in Education vs. Female Representation in Parliament') +xlab('disparity') +ylab('% of women in parliament')
```

Using the disparity values delineated in the previous section, disparity is plotted against the average percentage of women in parliament. Based on the regression line plotted above, there is no significant correlation between gender parity in education and female representation in legislature. This suggests that increased access to education does not necessarily increase women's representation in government. 


#### Concluding Remarks

From the data, we can see that as countries are closer to gender parity for education, women are more likely to spend more time in school. However, there is no significant indicator that gender parity in education correlates with a higher percentage of women in legislature. Access to equitable education may help women attain governmental positions but perhaps more needs to be done in other (cultural, social, and political) spheres to lead to equal representation in government.




